### ISSUE TITLE
 exclude squad is broken 

### ISSUE THREAD

**Issue by SKYNETCyber** [Radekj1/NR6-HAL#10]
For some reason exclude squad break hal in it appear the same way as spec ops does and hal will stop working. Might be a possible connection between both of them so may wanna look into that.
[mission.zip](https://github.com/user-attachments/files/16994159/mission.zip)

**Comment by Radekj1** [comment]
Testing progress: 
Exclude squad - The squad is not receiving any orders from HAL [default settings]. 
It is still being cached though and forced into default squad formation [if zbe cache module is placed]. 

Need example.

**Comment by Radekj1** [comment]
Exclude squad - workaround: 
Put it on all sides [even if you intend to have one squad excluded, like in evac], just make a squad on the edge of the map from second [and third if implemented] side and sync that squad to another exclude module. 

Remember - Don't sync module to commander - you don't want to exclude Hal commander from Hal 💯

**Comment by SKYNETCyber** [comment]
I remember many years ago someone mentioned that there is error in Exclude.sqf, that instead of "Excluded" there should be "ExcludedG"

You can check prt log and Exclude.sqf files -Thunderlord

**Comment by Radekj1** [comment]
Godef - I already did there something. Thunderlord synced hal commander with exclude, that broke it.

**Comment by Radekj1** [comment]
Fix on the way.  Need to upload right files, after a break...

**Comment by Radekj1** [comment]
Should be fixed now.
