### ISSUE TITLE
HAL_cargo_find

### ISSUE THREAD

**Issue by SKYNETCyber** [Radekj1/NR6-HAL#21]
In Commander Support Settings there is setting called "Cargo Find Range"
Based on the description, units should use any empty transports within the specified radius if they need to. 

In this scenario, I set the "Cargo Find Range" to 500 and placed 6 empty vehicles. When the mission starts, only one squad of 5 uses it, all the others go to the objective on foot.
You can spawn some new units with Zeus and they will not use vehicles too

[mission.zip](https://github.com/user-attachments/files/16994084/mission.zip)

**Comment by Radekj1** [comment]
Fixed [hopefully]
squads of at least 2+ people though work correctly.
