### ISSUE TITLE
HAL_objective_radius

### ISSUE THREAD

**Issue by SKYNETCyber** [Radekj1/NR6-HAL#23]
Issue with RydHQ_CaptureDistance (Capture Radius Mult)
Same basic setup. I only changed Chance Skip Recon to 1000 (RydHQ_NoRec), Capture Strenght (RydHQ_CaptLimit) to 100 and Capture Radius Mult (RydHQ_CaptureDistance) to 5
Start the mission and you will see that RydHQ_CaptureDistance is only applied to the first 3 sqauds, the default setting is applied to the rest

![1](https://github.com/user-attachments/assets/928b506b-ccdf-464f-ad83-a24355f88116)

[mission.zip](https://github.com/user-attachments/files/16994233/mission.zip)

**Comment by Radekj1** [comment]
Not a bug, but a feature as I say. 
Sending majority of the forces inside with additional squads surrounding to check for the possible enemies nearby / flank the city. 
After reaching the "outside" task, they get a new one to move into the city proper. 
So not a bug, but check for enemies.
