### ISSUE TITLE
HAL_objectives_description_radius

### ISSUE THREAD

**Issue by SKYNETCyber** [Radekj1/NR6-HAL#25]
There is 2 settings in Commander Onjectives Settings - Friendly/Enemy Capture Radius. 
Their description is wrong, they should be swapped - Friendly/Enemy

In this scenario I set Friendly to 1500 and Enemy to 500. BLUFOR control objective from start. 
Start scenario, wait some time for HAL to initialize, open Zeus spawn just random OPFOR unit 1100-1450m away from objective. 
You will immediately see a notification that the objective is lost. Objective can be captured only when BLUFOR units will be in 500m radius from it.

[mission.zip](https://github.com/user-attachments/files/16994252/mission.zip)

**Comment by Radekj1** [comment]
Fixed now 15 September 2024
