### ISSUE TITLE
HAL_startup_delay

### ISSUE THREAD

**Issue by SKYNETCyber** [Radekj1/NR6-HAL#26]
The startup delay is always 15 seconds no matter what you have set in the HAL Core module. 
In this scenario, the value is set to 60, but the HAL always initializes after 15 seconds.

Can be fixed by putting "RydHQ_Wait = 60" in core module init field. 
[mission.zip](https://github.com/user-attachments/files/16994266/mission.zip)

**Comment by Radekj1** [comment]
Just fixed
