### ISSUE TITLE
HAL_supports_error

### ISSUE THREAD

**Issue by SKYNETCyber** [Radekj1/NR6-HAL#27]
HAL gives some errors after using support trucks. 

Start mission, accelerate time. After 3-4 minutes HAL will send 2 support trucks to nearby vehicles. When they are done you will see an error. I think supports trying to return to the original position but can't because of a bug in the code

Return to editor and place Supports Rally Point module, set Chance of Rally to 100.
Start scenario and after 4-5 minutes there will be another error.

[mission.zip](https://github.com/user-attachments/files/16994277/mission.zip)

**Comment by Radekj1** [comment]
Fixed 15 Sep 2024
